version: '3.3'
services:
  db:
    // DBのVERSIONを決める
    image: mysql:5.7
    restart: always
    // DBのデータをセットアップする
    environment:
      MYSQL_DATABASE: 'db_name'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
   driver: local

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-js
    volumes:
      - ./docker-node/
    ports:
      - 3000:3000
    working_dir: "/docker-node"    
    command: sh -c 'npm i && nodemon'